// import { Metadata } from "next";

// export const metadata: Metadata = {
//   title: 'Watching',
//   description: 'Generated by create next app',
//   verification: {
//     google: 'S664YpT-7_myf-ca76-tavenmtnw031bDi4DJipw3Ms',
//   },
// };
